/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CommentsList: typeof import('./src/components/board/CommentsList.vue')['default']
    CountLabel: typeof import('./src/components/profile/CountLabel.vue')['default']
    CreateCommentForm: typeof import('./src/components/board/CreateCommentForm.vue')['default']
    CreateMatchingCommentForm: typeof import('./src/components/matching/CreateMatchingCommentForm.vue')['default']
    CreateMatchingForm: typeof import('./src/components/matching/CreateMatchingForm.vue')['default']
    CreateNoticePostForm: typeof import('./src/components/board/CreateNoticePostForm.vue')['default']
    CreatePostForm: typeof import('./src/components/board/CreatePostForm.vue')['default']
    CustomHeader: typeof import('./src/components/common/CustomHeader.vue')['default']
    Forbidden: typeof import('./src/components/error/Forbidden.vue')['default']
    InsertTextForm: typeof import('./src/components/sign/InsertTextForm.vue')['default']
    InternalServerError: typeof import('./src/components/error/InternalServerError.vue')['default']
    Layout: typeof import('./src/components/common/Layout.vue')['default']
    MatchingCommentCard: typeof import('./src/components/matching/MatchingCommentCard.vue')['default']
    MatchingPagination: typeof import('./src/components/common/MatchingPagination.vue')['default']
    MatchingPopup: typeof import('./src/components/matching/MatchingPopup.vue')['default']
    MatchingPostCard: typeof import('./src/components/matching/MatchingPostCard.vue')['default']
    MentorMenteeContext: typeof import('./src/components/profile/MentorMenteeContext.vue')['default']
    NoContent: typeof import('./src/components/error/NoContent.vue')['default']
    NotFound: typeof import('./src/components/error/NotFound.vue')['default']
    NoticePageBreadcrumb: typeof import('./src/components/common/NoticePageBreadcrumb.vue')['default']
    OTPVerify: typeof import('./src/components/sign/OTPVerify.vue')['default']
    PageBreadcrumb: typeof import('./src/components/common/PageBreadcrumb.vue')['default']
    Pagination: typeof import('./src/components/common/Pagination.vue')['default']
    PostsList: typeof import('./src/components/board/PostsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchActionBar: typeof import('./src/components/common/SearchActionBar.vue')['default']
    UpdateMentorMenteeForm: typeof import('./src/components/profile/UpdateMentorMenteeForm.vue')['default']
    UpdateProfileForm: typeof import('./src/components/profile/UpdateProfileForm.vue')['default']
  }
}
