/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CommentsList: typeof import('./src/components/board/CommentsList.vue')['default']
    CountLabel: typeof import('./src/components/profile/CountLabel.vue')['default']
    CreateCommentForm: typeof import('./src/components/board/CreateCommentForm.vue')['default']
    CreateMatchingCommentForm: typeof import('./src/components/matching/CreateMatchingCommentForm.vue')['default']
    CreateMatchingForm: typeof import('./src/components/matching/CreateMatchingForm.vue')['default']
    CreatePostForm: typeof import('./src/components/board/CreatePostForm.vue')['default']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InsertTextForm: typeof import('./src/components/sign/InsertTextForm.vue')['default']
    LogoTap: typeof import('./src/components/common/LogoTap.vue')['default']
    MatchingCommentCard: typeof import('./src/components/matching/MatchingCommentCard.vue')['default']
    MatchingPopup: typeof import('./src/components/matching/MatchingPopup.vue')['default']
    MatchingPostCard: typeof import('./src/components/matching/MatchingPostCard.vue')['default']
    MentorMenteeContext: typeof import('./src/components/profile/MentorMenteeContext.vue')['default']
    PageTop: typeof import('./src/components/common/PageTop.vue')['default']
    PostsList: typeof import('./src/components/board/PostsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UpdateMentorMenteeForm: typeof import('./src/components/profile/UpdateMentorMenteeForm.vue')['default']
    UpdateProfileForm: typeof import('./src/components/profile/UpdateProfileForm.vue')['default']
  }
}
