<template>
    <v-container fluid class="px-6">
    
      <!-- 상단 바 -->
      <v-row align="center" class="mt-6 mb-4">
        <v-col cols="12" md="6">
          <PageBreadcrumb />
        </v-col>
        <v-col cols="12" md="6" class="d-flex justify-end align-center">
          <div class="d-flex gap-2 align-center">
            <SearchActionBar />
            <v-btn color="primary" @click="showForm = true">작성</v-btn>
          </div>
        </v-col>
      </v-row>
  
      <!-- 카드 리스트 + 페이지네이션 -->
      <v-card class="pa-6 match-card-container" elevation="3" color="white">
        <MatchingPagination :cards="cardData" />
      </v-card>
  
      <!-- 작성 팝업 -->
      <CreateMatchingForm v-model:dialog="showForm" />
    </v-container>
  </template>
  
  <script setup lang="ts">
  import { ref } from 'vue'
  import PageBreadcrumb from '@/components/common/PageBreadcrumb.vue'
  import SearchActionBar from '@/components/common/SearchActionBar.vue'
  import MatchingPagination from '@/components/common/MatchingPagination.vue'
  import CreateMatchingForm from '@/components/matching/CreateMatchingForm.vue'
  
  const showForm = ref(false)
  
  const cardData = [
    {
      image: 'https://randomuser.me/api/portraits/women/86.jpg',
      name: '연정',
      title: '머피의 법칙(Rock ver)',
      career: '3년차',
      job: '웹 개발 프로그래머',
      tags: ['C언어', '자바', '파이썬'],
      company: '그루엔 엔터테인먼트',
      info: `서경대 재학하며 기타 세션 활동 및 유튜브 참여.\n자작곡 '머피의 법칙', '놀이터' 등을 발표.`,
      introduction: `초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다! 초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다! 초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다! 초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다! 초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다! 초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다! 초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다! 초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다! 초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다! 초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다! 초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다! 초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다! 초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다! 초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다! 초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다! 초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다!`,
    },
    {
      image: 'https://randomuser.me/api/portraits/women/87.jpg',
      name: '연정',
      title: '머피의 법칙(Rock ver)',
      career: '3년차',
      job: '웹 개발 프로그래머',
      tags: ['C언어', '자바', '파이썬'],
      company: '그루엔 엔터테인먼트',
      info: `서경대 재학하며 기타 세션 활동 및 유튜브 참여.\n자작곡 '머피의 법칙', '놀이터' 등을 발표.`,
      introduction: `초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다!`,
    },
    {
      image: 'https://randomuser.me/api/portraits/women/85.jpg',
      name: '연정',
      title: '머피의 법칙(Rock ver)',
      career: '3년차',
      job: '웹 개발 프로그래머',
      tags: ['C언어', '자바', '파이썬'],
      company: '그루엔 엔터테인먼트',
      info: `서경대 재학하며 기타 세션 활동 및 유튜브 참여.\n자작곡 '머피의 법칙', '놀이터' 등을 발표.`,
      introduction: `초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다!`,
    },
    {
      image: 'https://randomuser.me/api/portraits/women/86.jpg',
      name: '연정',
      title: '머피의 법칙(Rock ver)',
      career: '3년차',
      job: '웹 개발 프로그래머',
      tags: ['C언어', '자바', '파이썬'],
      company: '그루엔 엔터테인먼트',
      info: `서경대 재학하며 기타 세션 활동 및 유튜브 참여.\n자작곡 '머피의 법칙', '놀이터' 등을 발표.`,
      introduction: `초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다!`,
    },
    {
      image: 'https://randomuser.me/api/portraits/women/87.jpg',
      name: '연정',
      title: '머피의 법칙(Rock ver)',
      career: '3년차',
      job: '웹 개발 프로그래머',
      tags: ['C언어', '자바', '파이썬'],
      company: '그루엔 엔터테인먼트',
      info: `서경대 재학하며 기타 세션 활동 및 유튜브 참여.\n자작곡 '머피의 법칙', '놀이터' 등을 발표.`,
      introduction: `초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다!`,
    },
    {
      image: 'https://randomuser.me/api/portraits/women/85.jpg',
      name: '연정',
      title: '머피의 법칙(Rock ver)',
      career: '3년차',
      job: '웹 개발 프로그래머',
      tags: ['C언어', '자바', '파이썬'],
      company: '그루엔 엔터테인먼트',
      info: `서경대 재학하며 기타 세션 활동 및 유튜브 참여.\n자작곡 '머피의 법칙', '놀이터' 등을 발표.`,
      introduction: `초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다!`,
    },
    {
      image: 'https://randomuser.me/api/portraits/women/86.jpg',
      name: '연정',
      title: '머피의 법칙(Rock ver)',
      career: '3년차',
      job: '웹 개발 프로그래머',
      tags: ['C언어', '자바', '파이썬'],
      company: '그루엔 엔터테인먼트',
      info: `서경대 재학하며 기타 세션 활동 및 유튜브 참여.\n자작곡 '머피의 법칙', '놀이터' 등을 발표.`,
      introduction: `초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다!`,
    },
    {
      image: 'https://randomuser.me/api/portraits/women/87.jpg',
      name: '연정',
      title: '머피의 법칙(Rock ver)',
      career: '3년차',
      job: '웹 개발 프로그래머',
      tags: ['C언어', '자바', '파이썬'],
      company: '그루엔 엔터테인먼트',
      info: `서경대 재학하며 기타 세션 활동 및 유튜브 참여.\n자작곡 '머피의 법칙', '놀이터' 등을 발표.`,
      introduction: `초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다!`,
    },
    {
      image: 'https://randomuser.me/api/portraits/women/85.jpg',
      name: '연정',
      title: '머피의 법칙(Rock ver)',
      career: '3년차',
      job: '웹 개발 프로그래머',
      tags: ['C언어', '자바', '파이썬'],
      company: '그루엔 엔터테인먼트',
      info: `서경대 재학하며 기타 세션 활동 및 유튜브 참여.\n자작곡 '머피의 법칙', '놀이터' 등을 발표.`,
      introduction: `초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다!`,
    },
    {
      image: 'https://randomuser.me/api/portraits/women/86.jpg',
      name: '연정',
      title: '머피의 법칙(Rock ver)',
      career: '3년차',
      job: '웹 개발 프로그래머',
      tags: ['C언어', '자바', '파이썬'],
      company: '그루엔 엔터테인먼트',
      info: `서경대 재학하며 기타 세션 활동 및 유튜브 참여.\n자작곡 '머피의 법칙', '놀이터' 등을 발표.`,
      introduction: `초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다!`,
    },
    {
      image: 'https://randomuser.me/api/portraits/women/87.jpg',
      name: '연정',
      title: '머피의 법칙(Rock ver)',
      career: '3년차',
      job: '웹 개발 프로그래머',
      tags: ['C언어', '자바', '파이썬'],
      company: '그루엔 엔터테인먼트',
      info: `서경대 재학하며 기타 세션 활동 및 유튜브 참여.\n자작곡 '머피의 법칙', '놀이터' 등을 발표.`,
      introduction: `초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다!`,
    },
    {
      image: 'https://randomuser.me/api/portraits/women/85.jpg',
      name: '연정',
      title: '머피의 법칙(Rock ver)',
      career: '3년차',
      job: '웹 개발 프로그래머',
      tags: ['C언어', '자바', '파이썬'],
      company: '그루엔 엔터테인먼트',
      info: `서경대 재학하며 기타 세션 활동 및 유튜브 참여.\n자작곡 '머피의 법칙', '놀이터' 등을 발표.`,
      introduction: `초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다!`,
    },
    {
      image: 'https://randomuser.me/api/portraits/women/86.jpg',
      name: '연정',
      title: '머피의 법칙(Rock ver)',
      career: '3년차',
      job: '웹 개발 프로그래머',
      tags: ['C언어', '자바', '파이썬'],
      company: '그루엔 엔터테인먼트',
      info: `서경대 재학하며 기타 세션 활동 및 유튜브 참여.\n자작곡 '머피의 법칙', '놀이터' 등을 발표.`,
      introduction: `초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다!`,
    },
    {
      image: 'https://randomuser.me/api/portraits/women/87.jpg',
      name: '연정',
      title: '머피의 법칙(Rock ver)',
      career: '3년차',
      job: '웹 개발 프로그래머',
      tags: ['C언어', '자바', '파이썬'],
      company: '그루엔 엔터테인먼트',
      info: `서경대 재학하며 기타 세션 활동 및 유튜브 참여.\n자작곡 '머피의 법칙', '놀이터' 등을 발표.`,
      introduction: `초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다!`,
    },
    {
      image: 'https://randomuser.me/api/portraits/women/85.jpg',
      name: '연정',
      title: '머피의 법칙(Rock ver)',
      career: '3년차',
      job: '웹 개발 프로그래머',
      tags: ['C언어', '자바', '파이썬'],
      company: '그루엔 엔터테인먼트',
      info: `서경대 재학하며 기타 세션 활동 및 유튜브 참여.\n자작곡 '머피의 법칙', '놀이터' 등을 발표.`,
      introduction: `초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다!`,
    },
    {
      image: 'https://randomuser.me/api/portraits/women/86.jpg',
      name: '연정',
      title: '머피의 법칙(Rock ver)',
      career: '3년차',
      job: '웹 개발 프로그래머',
      tags: ['C언어', '자바', '파이썬'],
      company: '그루엔 엔터테인먼트',
      info: `서경대 재학하며 기타 세션 활동 및 유튜브 참여.\n자작곡 '머피의 법칙', '놀이터' 등을 발표.`,
      introduction: `초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다!`,
    },
    {
      image: 'https://randomuser.me/api/portraits/women/87.jpg',
      name: '연정',
      title: '머피의 법칙(Rock ver)',
      career: '3년차',
      job: '웹 개발 프로그래머',
      tags: ['C언어', '자바', '파이썬'],
      company: '그루엔 엔터테인먼트',
      info: `서경대 재학하며 기타 세션 활동 및 유튜브 참여.\n자작곡 '머피의 법칙', '놀이터' 등을 발표.`,
      introduction: `초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다!`,
    },
    {
      image: 'https://randomuser.me/api/portraits/women/85.jpg',
      name: '연정',
      title: '머피의 법칙(Rock ver)',
      career: '3년차',
      job: '웹 개발 프로그래머',
      tags: ['C언어', '자바', '파이썬'],
      company: '그루엔 엔터테인먼트',
      info: `서경대 재학하며 기타 세션 활동 및 유튜브 참여.\n자작곡 '머피의 법칙', '놀이터' 등을 발표.`,
      introduction: `초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다!`,
    },
    {
      image: 'https://randomuser.me/api/portraits/women/86.jpg',
      name: '연정',
      title: '머피의 법칙(Rock ver)',
      career: '3년차',
      job: '웹 개발 프로그래머',
      tags: ['C언어', '자바', '파이썬'],
      company: '그루엔 엔터테인먼트',
      info: `서경대 재학하며 기타 세션 활동 및 유튜브 참여.\n자작곡 '머피의 법칙', '놀이터' 등을 발표.`,
      introduction: `초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다!`,
    },
    {
      image: 'https://randomuser.me/api/portraits/women/87.jpg',
      name: '연정',
      title: '머피의 법칙(Rock ver)',
      career: '3년차',
      job: '웹 개발 프로그래머',
      tags: ['C언어', '자바', '파이썬'],
      company: '그루엔 엔터테인먼트',
      info: `서경대 재학하며 기타 세션 활동 및 유튜브 참여.\n자작곡 '머피의 법칙', '놀이터' 등을 발표.`,
      introduction: `초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다!`,
    },
    {
      image: 'https://randomuser.me/api/portraits/women/85.jpg',
      name: '연정',
      title: '머피의 법칙(Rock ver)',
      career: '3년차',
      job: '웹 개발 프로그래머',
      tags: ['C언어', '자바', '파이썬'],
      company: '그루엔 엔터테인먼트',
      info: `서경대 재학하며 기타 세션 활동 및 유튜브 참여.\n자작곡 '머피의 법칙', '놀이터' 등을 발표.`,
      introduction: `초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다!`,
    },
    {
      image: 'https://randomuser.me/api/portraits/women/86.jpg',
      name: '연정',
      title: '머피의 법칙(Rock ver)',
      career: '3년차',
      job: '웹 개발 프로그래머',
      tags: ['C언어', '자바', '파이썬'],
      company: '그루엔 엔터테인먼트',
      info: `서경대 재학하며 기타 세션 활동 및 유튜브 참여.\n자작곡 '머피의 법칙', '놀이터' 등을 발표.`,
      introduction: `초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다!`,
    },
    {
      image: 'https://randomuser.me/api/portraits/women/87.jpg',
      name: '연정',
      title: '머피의 법칙(Rock ver)',
      career: '3년차',
      job: '웹 개발 프로그래머',
      tags: ['C언어', '자바', '파이썬'],
      company: '그루엔 엔터테인먼트',
      info: `서경대 재학하며 기타 세션 활동 및 유튜브 참여.\n자작곡 '머피의 법칙', '놀이터' 등을 발표.`,
      introduction: `초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다!`,
    },
    {
      image: 'https://randomuser.me/api/portraits/women/85.jpg',
      name: '연정',
      title: '머피의 법칙(Rock ver)',
      career: '3년차',
      job: '웹 개발 프로그래머',
      tags: ['C언어', '자바', '파이썬'],
      company: '그루엔 엔터테인먼트',
      info: `서경대 재학하며 기타 세션 활동 및 유튜브 참여.\n자작곡 '머피의 법칙', '놀이터' 등을 발표.`,
      introduction: `초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다!`,
    },
    {
      image: 'https://randomuser.me/api/portraits/women/86.jpg',
      name: '연정',
      title: '머피의 법칙(Rock ver)',
      career: '3년차',
      job: '웹 개발 프로그래머',
      tags: ['C언어', '자바', '파이썬'],
      company: '그루엔 엔터테인먼트',
      info: `서경대 재학하며 기타 세션 활동 및 유튜브 참여.\n자작곡 '머피의 법칙', '놀이터' 등을 발표.`,
      introduction: `초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다!`,
    },
    {
      image: 'https://randomuser.me/api/portraits/women/87.jpg',
      name: '연정',
      title: '머피의 법칙(Rock ver)',
      career: '3년차',
      job: '웹 개발 프로그래머',
      tags: ['C언어', '자바', '파이썬'],
      company: '그루엔 엔터테인먼트',
      info: `서경대 재학하며 기타 세션 활동 및 유튜브 참여.\n자작곡 '머피의 법칙', '놀이터' 등을 발표.`,
      introduction: `초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다!`,
    },
    {
      image: 'https://randomuser.me/api/portraits/women/85.jpg',
      name: '연정',
      title: '머피의 법칙(Rock ver)',
      career: '3년차',
      job: '웹 개발 프로그래머',
      tags: ['C언어', '자바', '파이썬'],
      company: '그루엔 엔터테인먼트',
      info: `서경대 재학하며 기타 세션 활동 및 유튜브 참여.\n자작곡 '머피의 법칙', '놀이터' 등을 발표.`,
      introduction: `초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다!`,
    },
    {
      image: 'https://randomuser.me/api/portraits/women/86.jpg',
      name: '연정',
      title: '머피의 법칙(Rock ver)',
      career: '3년차',
      job: '웹 개발 프로그래머',
      tags: ['C언어', '자바', '파이썬'],
      company: '그루엔 엔터테인먼트',
      info: `서경대 재학하며 기타 세션 활동 및 유튜브 참여.\n자작곡 '머피의 법칙', '놀이터' 등을 발표.`,
      introduction: `초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다!`,
    },
    {
      image: 'https://randomuser.me/api/portraits/women/87.jpg',
      name: '연정',
      title: '머피의 법칙(Rock ver)',
      career: '3년차',
      job: '웹 개발 프로그래머',
      tags: ['C언어', '자바', '파이썬'],
      company: '그루엔 엔터테인먼트',
      info: `서경대 재학하며 기타 세션 활동 및 유튜브 참여.\n자작곡 '머피의 법칙', '놀이터' 등을 발표.`,
      introduction: `초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다!`,
    },
    {
      image: 'https://randomuser.me/api/portraits/women/85.jpg',
      name: '연정',
      title: '머피의 법칙(Rock ver)',
      career: '3년차',
      job: '웹 개발 프로그래머',
      tags: ['C언어', '자바', '파이썬'],
      company: '그루엔 엔터테인먼트',
      info: `서경대 재학하며 기타 세션 활동 및 유튜브 참여.\n자작곡 '머피의 법칙', '놀이터' 등을 발표.`,
      introduction: `초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다!`,
    },
    {
      image: 'https://randomuser.me/api/portraits/women/86.jpg',
      name: '연정',
      title: '머피의 법칙(Rock ver)',
      career: '3년차',
      job: '웹 개발 프로그래머',
      tags: ['C언어', '자바', '파이썬'],
      company: '그루엔 엔터테인먼트',
      info: `서경대 재학하며 기타 세션 활동 및 유튜브 참여.\n자작곡 '머피의 법칙', '놀이터' 등을 발표.`,
      introduction: `초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다!`,
    },
    {
      image: 'https://randomuser.me/api/portraits/women/87.jpg',
      name: '연정',
      title: '머피의 법칙(Rock ver)',
      career: '3년차',
      job: '웹 개발 프로그래머',
      tags: ['C언어', '자바', '파이썬'],
      company: '그루엔 엔터테인먼트',
      info: `서경대 재학하며 기타 세션 활동 및 유튜브 참여.\n자작곡 '머피의 법칙', '놀이터' 등을 발표.`,
      introduction: `초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다!`,
    },
    {
      image: 'https://randomuser.me/api/portraits/women/85.jpg',
      name: '연정',
      title: '머피의 법칙(Rock ver)',
      career: '3년차',
      job: '웹 개발 프로그래머',
      tags: ['C언어', '자바', '파이썬'],
      company: '그루엔 엔터테인먼트',
      info: `서경대 재학하며 기타 세션 활동 및 유튜브 참여.\n자작곡 '머피의 법칙', '놀이터' 등을 발표.`,
      introduction: `초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다!`,
    },
    {
      image: 'https://randomuser.me/api/portraits/women/86.jpg',
      name: '연정',
      title: '머피의 법칙(Rock ver)',
      career: '3년차',
      job: '웹 개발 프로그래머',
      tags: ['C언어', '자바', '파이썬'],
      company: '그루엔 엔터테인먼트',
      info: `서경대 재학하며 기타 세션 활동 및 유튜브 참여.\n자작곡 '머피의 법칙', '놀이터' 등을 발표.`,
      introduction: `초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다!`,
    },
    {
      image: 'https://randomuser.me/api/portraits/women/87.jpg',
      name: '연정',
      title: '머피의 법칙(Rock ver)',
      career: '3년차',
      job: '웹 개발 프로그래머',
      tags: ['C언어', '자바', '파이썬'],
      company: '그루엔 엔터테인먼트',
      info: `서경대 재학하며 기타 세션 활동 및 유튜브 참여.\n자작곡 '머피의 법칙', '놀이터' 등을 발표.`,
      introduction: `초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다!`,
    },
    {
      image: 'https://randomuser.me/api/portraits/women/85.jpg',
      name: '연정',
      title: '머피의 법칙(Rock ver)',
      career: '3년차',
      job: '웹 개발 프로그래머',
      tags: ['C언어', '자바', '파이썬'],
      company: '그루엔 엔터테인먼트',
      info: `서경대 재학하며 기타 세션 활동 및 유튜브 참여.\n자작곡 '머피의 법칙', '놀이터' 등을 발표.`,
      introduction: `초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다!`,
    },
    {
      image: 'https://randomuser.me/api/portraits/women/86.jpg',
      name: '연정',
      title: '머피의 법칙(Rock ver)',
      career: '3년차',
      job: '웹 개발 프로그래머',
      tags: ['C언어', '자바', '파이썬'],
      company: '그루엔 엔터테인먼트',
      info: `서경대 재학하며 기타 세션 활동 및 유튜브 참여.\n자작곡 '머피의 법칙', '놀이터' 등을 발표.`,
      introduction: `초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다!`,
    },
    {
      image: 'https://randomuser.me/api/portraits/women/87.jpg',
      name: '연정',
      title: '머피의 법칙(Rock ver)',
      career: '3년차',
      job: '웹 개발 프로그래머',
      tags: ['C언어', '자바', '파이썬'],
      company: '그루엔 엔터테인먼트',
      info: `서경대 재학하며 기타 세션 활동 및 유튜브 참여.\n자작곡 '머피의 법칙', '놀이터' 등을 발표.`,
      introduction: `초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다!`,
    },
    {
      image: 'https://randomuser.me/api/portraits/women/85.jpg',
      name: '연정',
      title: '머피의 법칙(Rock ver)',
      career: '3년차',
      job: '웹 개발 프로그래머',
      tags: ['C언어', '자바', '파이썬'],
      company: '그루엔 엔터테인먼트',
      info: `서경대 재학하며 기타 세션 활동 및 유튜브 참여.\n자작곡 '머피의 법칙', '놀이터' 등을 발표.`,
      introduction: `초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다!`,
    },
    {
      image: 'https://randomuser.me/api/portraits/women/86.jpg',
      name: '연정',
      title: '머피의 법칙(Rock ver)',
      career: '3년차',
      job: '웹 개발 프로그래머',
      tags: ['C언어', '자바', '파이썬'],
      company: '그루엔 엔터테인먼트',
      info: `서경대 재학하며 기타 세션 활동 및 유튜브 참여.\n자작곡 '머피의 법칙', '놀이터' 등을 발표.`,
      introduction: `초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다!`,
    },
    {
      image: 'https://randomuser.me/api/portraits/women/87.jpg',
      name: '연정',
      title: '머피의 법칙(Rock ver)',
      career: '3년차',
      job: '웹 개발 프로그래머',
      tags: ['C언어', '자바', '파이썬'],
      company: '그루엔 엔터테인먼트',
      info: `서경대 재학하며 기타 세션 활동 및 유튜브 참여.\n자작곡 '머피의 법칙', '놀이터' 등을 발표.`,
      introduction: `초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다!`,
    },
    {
      image: 'https://randomuser.me/api/portraits/women/85.jpg',
      name: '연정',
      title: '머피의 법칙(Rock ver)',
      career: '3년차',
      job: '웹 개발 프로그래머',
      tags: ['C언어', '자바', '파이썬'],
      company: '그루엔 엔터테인먼트',
      info: `서경대 재학하며 기타 세션 활동 및 유튜브 참여.\n자작곡 '머피의 법칙', '놀이터' 등을 발표.`,
      introduction: `초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다!`,
    },
    {
      image: 'https://randomuser.me/api/portraits/women/86.jpg',
      name: '연정',
      title: '머피의 법칙(Rock ver)',
      career: '3년차',
      job: '웹 개발 프로그래머',
      tags: ['C언어', '자바', '파이썬'],
      company: '그루엔 엔터테인먼트',
      info: `서경대 재학하며 기타 세션 활동 및 유튜브 참여.\n자작곡 '머피의 법칙', '놀이터' 등을 발표.`,
      introduction: `초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다!`,
    },
    {
      image: 'https://randomuser.me/api/portraits/women/87.jpg',
      name: '연정',
      title: '머피의 법칙(Rock ver)',
      career: '3년차',
      job: '웹 개발 프로그래머',
      tags: ['C언어', '자바', '파이썬'],
      company: '그루엔 엔터테인먼트',
      info: `서경대 재학하며 기타 세션 활동 및 유튜브 참여.\n자작곡 '머피의 법칙', '놀이터' 등을 발표.`,
      introduction: `초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다!`,
    },
    {
      image: 'https://randomuser.me/api/portraits/women/85.jpg',
      name: '연정',
      title: '머피의 법칙(Rock ver)',
      career: '3년차',
      job: '웹 개발 프로그래머',
      tags: ['C언어', '자바', '파이썬'],
      company: '그루엔 엔터테인먼트',
      info: `서경대 재학하며 기타 세션 활동 및 유튜브 참여.\n자작곡 '머피의 법칙', '놀이터' 등을 발표.`,
      introduction: `초등학교 시절 드럼에 매료 → 통기타 → 일렉기타로 진로 확정. 잘 부탁 드립니다!`,
    },
    
  ]
  </script>
  
  <style scoped>
  .match-card-container {
    background-color: white;
    border-radius: 12px;
    width: 100%;
  }
  </style>
  